export const categories = [
  "Animals",
  "Art",
  "Community Development",
  "Conservation",
  "Consumer",
  "Culture",
  "DeFi",
  "DAO",
  "Education",
  "Entertainment",
  "Environment",
  "Employment",
  "Family and Children",
  "Finance",
  "Food",
  "Gaming",
  "Gender Equality",
  "Health Care",
  "IoT",
  "Infrastructure",
  "NFT",
  "Metaverse",
  "Real Estate",
  "Religious",
  "Renewable Energy",
  "Research",
  "Science",
  "Social Impact",
  "Supply Chain",
  "Sustainability",
  "Tech",
];
